name: GPRealEstate
main: TownCraftServer.com.GPRealEstate.Main
version: 2.0.0
author: SuperPyroManiac
api-version: 1.16
depend: [GriefPrevention, Vault]

commands:
  gpre:
    description: Access to the GPRealEstate command.
    usage: /<command> ?
    aliases: [realestate, gprealestate]
    permission: gprealestate.info
    permission-message: You do not have access to that command!

permissions:
  gprealestate.*:
    description: Gives access to all GPRealEstate permissions.
    default: op
    children:
      gprealestate.info: true
      gprealestate.claim.buy: true
      gprealestate.claim.sell: true
      gprealestate.subclaim.buy: true
      gprealestate.subclaim.sell: true
      gprealestate.ignore.limit: true
      gprealestate.command: true
      gprealestate.admin: true
  gprealestate.claim.*:
    description: Gives access all claim access.
    default: op
    children:
      gprealestate.claim.buy: true
      gprealestate.claim.sell: true
  gprealestate.subclaim.*:
    description: Gives access all claim access.
    default: op
    children:
      gprealestate.subclaim.buy: true
      gprealestate.subclaim.sell: true
  gprealestate.info:
    description: Allows player to get claim info.
    default: true
  gprealestate.claim.buy:
    description: Allows player to buy claims.
    default: true
  gprealestate.claim.sell:
    description: Allows player to sell claims.
    default: true
  gprealestate.subclaim.buy:
    description: Allows player to buy subclaims.
    default: true
  gprealestate.subclaim.sell:
    description: Allows player to sell subclaims.
    default: true
  gprealestate.ignore.limit:
    description: Allows player to buy claims thats bigger than the players available claim size.
    default: false
  gprealestate.command:
    description: Allows the player to use commands.
    default: true
  gprealestate.admin:
    description: Allows the player to see information about the plugin.
    default: false